### ISSUE TITLE
Table clickable meta logic changed for slots

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/forms#34]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
In regards to this file: @enso-ui/tables/src/bulma/parts/TableCell.vue

Before 4.9.0 upgrade:
```
<span :class="cssClass"
        @click="meta.clickable ? $emit('clicked') : null">
        <slot v-if="meta.slot"
            :name="column.name">
            {{ value }}
        </slot>
```
Slot was defined after the cssClass injection and @click.

After 4.9.0 upgrade:
```
<slot v-if="meta.slot"
        :name="column.name">
        <span>
            {{ modelValue }}
        </span>
    </slot>
    <span :class="cssClass"
        @click="meta.clickable ? $emit('clicked') : null"
```

Separation was 100%, clickable will not be working anymore. Has to be implemented.

Was that wanted?
Should we update the documentation?

**Comment by aocneanu** [comment]
Hi @robbykrlos 

Since it's a slot, you can cascade the event yourself, (CSS class etc)

The reason we changed the slot declaration is to avoid enforcing a (generally useless span) around the slot content.

**Comment by robbykrlos** [comment]
Hi,

Thanks, will update the documentation if necessary.
